### ISSUE TITLE
I can't activate an invoice in BO through prestashop by changing status.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/prestashop#172]
Order # in prestashop: 122
Invoice #: 8371

**Comment by Boxedsolutions** [comment]
Should work now

**Comment by joakim-combain** [comment]
I can't activate a test order. Is this something we care about for this release? @andyjohansson

**Comment by andyjohansson** [comment]
I don't think it´s possible to activate those. But where can't you activate them?

**Comment by joakim-combain** [comment]
In the prestashop backend by changing order status. You can activate them if you put activatePayment in testmode. It should work atleast.

**Comment by andyjohansson** [comment]
Can you verify this with @yuxelfindik that it should be like that? If so then @Boxedsolutions have some things to sort out.

**Comment by joakim-combain** [comment]
I just tested it and it works to activate a test payment with activatePayment. Is there any reason it shouldn't work like this?

**Comment by andyjohansson** [comment]
Ok, then @Boxedsolutions should fix this.

**Comment by Boxedsolutions** [comment]
Its built so that it fetches testmode status for the different payment methods in the activate method. 

If you create the order in testmode, you will need to activate in testmode as the invoice doesnt exist while the modes doesnt match. 

I dont really get if it works or not in this conversation. @joakim-combain @andyjohansson

**Comment by andyjohansson** [comment]
@Boxedsolutions have verifed that it works.
