### ISSUE TITLE
Different orders in store and BO if you change the checkout and then finish the order with the correct amount. 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/prestashop#395]
![image](https://user-images.githubusercontent.com/58035708/106118085-02612480-6154-11eb-92b4-2e49957fecd7.png)
As can be seen above in the image above is it possible to create an order that differs in both BO and in prestashop that is accepted by both systems even if the content differs widely. This would result in the customer of the merchant getting an invoice email that differs from the order they actually ordered according to the store and what they assumedly receive. 

How to reproduce: 
1: Place an order that has items who's price you can match with another combination of item(s).
2: Open up the checkout and go to the step where you can complete the order.
3: Start the store again in a seperate tab. 
4: Empty the cart. 
5: Add new but separate items to match the price of the original purchase. 
6: Go back to the original tab.
7: Finish the purchase. 
8: Compare the order in BO and the prestashop store.

**Comment by andyjohansson** [comment]
Nicely identified edge case @OskarOstlund.

**Comment by KFoobar** [comment]
This is a known vulnerability in Prestashop's structure. Prestashop stores the shopping cart as a separate entity, an order is then created by converting a shopping cart into an order. Because the shopping cart is linked to session, it is open for manipulation during the payment process. 

What you can do is try to overwrite and recreate the shopping cart when creating the order, but it still leaves some room for manipulation and other issues.

**Comment by KFoobar** [comment]
@andyjohansson Basically the issue is that you can't "lock" the cart content. When the customer is sent to an external page to finalize the payment, you can modify the cart from another tab. The issue is not directly connected to Billmate Checkout.

To make an order in Prestashop, you have to load a cart from the database by id (the id stored in the session cookie), then convert it to an order.

The extension adds the cart id to the `PaymentData` property when a new checkout initiates. When the access/callback request is sent back to the store, the extension then loads the cart with the cart id attached within the payload. It loads the cart and converts it to an order. 

A workaround is to create a new cart with the items in from the `getPaymentInfo`-payload. It can mess things up for extensions that interacts with abandoned shopping carts etc. since each customer will get an "extra" cart that hasn't been converted in to an order.

**Comment by andyjohansson** [comment]
Platform behaviour.
