### ISSUE TITLE
Thank You Continue shopping button

### ISSUE THREAD

**Issue by MattiasNilsson** [Billmate/prestashop#397]
Continue shopping button missing on thank you page. We need to add it so customers can continue shopping after a purchase.

![image-2021-01-28-10-30-57-179](https://user-images.githubusercontent.com/1718315/106150456-aad6af00-617b-11eb-919a-88083a9923ec.png)

**Comment by andyjohansson** [comment]
In reality, why would we even have our own thank you page? Why don't navigate to the standard thank you page and insert the Checkout iframe there with thank you? That should be possible?
https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/
<img width="957" alt="Skärmavbild 2021-01-28 kl  20 06 13" src="https://user-images.githubusercontent.com/4968755/106186241-4d0a8d00-61a4-11eb-9df2-f7326bc5dcc8.png">

**Comment by OskarOstlund** [comment]
tested and approved under conditions;

the fix add a "Fortsätt shoppa" button as the task calls for, however it continues to redirect us to our own thank you page rather than inserting our iframe into the native thank you page as  @andyjohansson requested. Is this good enough or do we have to use the inserted solution?

**Comment by andyjohansson** [comment]
For new we use the way it's working. We will have to change this in the future however..

**Comment by stefanliden** [comment]
Tested and this works well :)

**Comment by stefanliden** [comment]
Tested and this works well :)
