### ISSUE TITLE
No update API call on bankPayments. 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/prestashop#398]
![image](https://user-images.githubusercontent.com/58035708/106430777-912fb300-646c-11eb-9e82-e6a5437f9f50.png)

In the picture attached above is there three types of AddPayment API calls made to BO, in descending order are those;  card payment, invoice, and a bank payment. Highlighted in green is the original AddPayment API call and highlighted in yellow is the following update payment API calls that updates the order number in BO. 

![image](https://user-images.githubusercontent.com/58035708/106432340-dd7bf280-646e-11eb-974f-8ec644572e9d.png)
As can be seen in the issue attached above does this cause different order numbers in BO and the prestashop store.

**Comment by andyjohansson** [comment]
This might, be due to the fact that bank payments are "final" and we cannot update the order ID to Trustly. However, our own "reciept" we can update anyway if you make an "updatePayment" request. Can you verify this @OskarOstlund manually through the API by first making a purchase using payment method 16 and than making an updatePayment and just updating the order id. Just to make sure that the API supports the action before we start fixing anything here.

**Comment by OskarOstlund** [comment]
At least when testing this did updatePayments not do anything to the test invoice's order number when the payment method was 16. However it worked with other payment methods so it seems this is a case with bankpayment in particular. 

I know that the new woocommerce module send in the correct ordernumber to begin with to us but I am not sure if this is possible in Prestashop or not.

**Comment by andyjohansson** [comment]
I have PM:ed you @OskarOstlund. Let's have a chat about this issue.
